"""dtollib — Experiment-facing DT-Open Layers acquisition layer.

``dtollib`` is a typed, lifecycle-managed acquisition layer over a
hand-rolled ``ctypes`` binding to the Data Translation DataAcq SDK. It
fits the same scientific-instrumentation ecosystem as ``alicatlib``,
``sartoriuslib``, ``watlowlib``, and ``nidaqlib``.

Core API is ``async`` (built on ``anyio``); a sync facade is available at
:mod:`dtollib.sync` for scripts, notebooks, and REPL use.

Single-value analog input/output and digital I/O run through
:meth:`DtolSession.poll` / :meth:`DtolSession.write`; continuous analog
input streams through :func:`dtollib.streaming.record`.
"""

from __future__ import annotations

from dtollib.channels import channel_from_dict
from dtollib.channels.analog_input import (
    AnalogInputBase,
    AnalogInputVoltage,
    BridgeConfiguration,
    BridgeInput,
    ChannelType,
    CjcSource,
    CouplingType,
    CurrentInput,
    Encoding,
    ExcitationSource,
    FilterType,
    IepeInput,
    ResistanceInput,
    RtdInput,
    RtdType,
    StrainExcitationSource,
    StrainGageConfiguration,
    StrainInput,
    TemperatureUnit,
    ThermistorInput,
    ThermocoupleInput,
    ThermocoupleType,
)
from dtollib.channels.analog_output import AnalogOutputVoltage
from dtollib.channels.base import ChannelSpec
from dtollib.channels.counter_input import (
    CounterEdgeCount,
    CounterEdgeToEdge,
    CounterFrequency,
    QuadratureDecoder,
    Tachometer,
)
from dtollib.channels.counter_output import (
    OneShotOutput,
    PulseTrainOutput,
    RepetitiveOneShotOutput,
)
from dtollib.channels.digital import (
    DigitalInputPort,
    DigitalLine,
    DigitalOutputPort,
)
from dtollib.config import DEFAULT_ENV_PREFIX, DtolConfig, config_from_env
from dtollib.errors import (
    DtolBackendError,
    DtolBufferOverrunError,
    DtolBufferUnderrunError,
    DtolCapabilityError,
    DtolCapiError,
    DtolConfigurationError,
    DtolConfirmationRequiredError,
    DtolDependencyError,
    DtolError,
    DtolReadError,
    DtolResourceError,
    DtolSinkDependencyError,
    DtolSinkError,
    DtolSinkSchemaError,
    DtolSinkWriteError,
    DtolTaskStateError,
    DtolTimeoutError,
    DtolTriggerError,
    DtolValidationError,
    DtolWriteError,
    ErrorContext,
)
from dtollib.errors import (
    DtolConnectionError as DtolConnectionError,
)
from dtollib.errors import (
    DtolTransientError as DtolTransientError,
)
from dtollib.factory import open_device
from dtollib.manager import DeviceResult, DtolManager
from dtollib.sinks.base import block_to_rows
from dtollib.sinks.base import reading_to_row as reading_to_row
from dtollib.strain import bridge_value_from_volts, strain_from_volts
from dtollib.streaming import (
    AcquisitionSummary,
    ErrorPolicy,
    OverflowPolicy,
    PlaybackSource,
    Recording,
    play,
    record,
    record_polled,
)
from dtollib.system import (
    BoardInfo,
    CapabilitySet,
    DeviceInfo,
    SubsystemInfo,
    find_devices,
    find_subsystems,
)
from dtollib.tasks import (
    AnalogThresholdStart,
    BufferPlan,
    BufferState,
    ClockSource,
    CounterMode,
    DaqBlock,
    DaqReading,
    DaqSample,
    DataFlow,
    DtolSession,
    Edge,
    ExternalDigitalStart,
    GateType,
    IOType,
    PulseType,
    QuadratureDecodeMode,
    QueueStrategy,
    RawLogging,
    ReferenceTrigger,
    RetriggerMode,
    RetriggerSpec,
    SdkEventKind,
    SensorStatus,
    SoftwareStart,
    SubsystemState,
    SubsystemType,
    SyncBusStart,
    TaskBuilder,
    TaskSpec,
    Timing,
    TriggerSpec,
    WrapMode,
    block_to_long_rows,
)
from dtollib.teds import (
    BridgeSensorTeds,
    StrainGageTeds,
    read_bridge_sensor_teds,
    read_bridge_sensor_virtual_teds,
    read_strain_gage_teds,
    read_strain_gage_virtual_teds,
)
from dtollib.units import to_pint
from dtollib.utils import (
    compute_delta_rosette,
    compute_rectangular_rosette,
    convert_temperature_to_volts,
    convert_volts_to_temperature,
    get_thermocouple_range,
)
from dtollib.version import __version__

__all__ = [
    "DEFAULT_ENV_PREFIX",
    "AcquisitionSummary",
    "AnalogInputBase",
    "AnalogInputVoltage",
    "AnalogOutputVoltage",
    "AnalogThresholdStart",
    "BoardInfo",
    "BridgeConfiguration",
    "BridgeInput",
    "BridgeSensorTeds",
    "BufferPlan",
    "BufferState",
    "CapabilitySet",
    "ChannelSpec",
    "ChannelType",
    "CjcSource",
    "ClockSource",
    "CounterEdgeCount",
    "CounterEdgeToEdge",
    "CounterFrequency",
    "CounterMode",
    "CouplingType",
    "CurrentInput",
    "DaqBlock",
    "DaqReading",
    "DaqSample",
    "DataFlow",
    "DeviceInfo",
    "DeviceResult",
    "DigitalInputPort",
    "DigitalLine",
    "DigitalOutputPort",
    "DtolBackendError",
    "DtolBufferOverrunError",
    "DtolBufferUnderrunError",
    "DtolCapabilityError",
    "DtolCapiError",
    "DtolConfig",
    "DtolConfigurationError",
    "DtolConfirmationRequiredError",
    "DtolConnectionError",
    "DtolDependencyError",
    "DtolError",
    "DtolManager",
    "DtolReadError",
    "DtolResourceError",
    "DtolSession",
    "DtolSinkDependencyError",
    "DtolSinkError",
    "DtolSinkSchemaError",
    "DtolSinkWriteError",
    "DtolTaskStateError",
    "DtolTimeoutError",
    "DtolTransientError",
    "DtolTriggerError",
    "DtolValidationError",
    "DtolWriteError",
    "Edge",
    "Encoding",
    "ErrorContext",
    "ErrorPolicy",
    "ExcitationSource",
    "ExternalDigitalStart",
    "FilterType",
    "GateType",
    "IOType",
    "IepeInput",
    "OneShotOutput",
    "OverflowPolicy",
    "PlaybackSource",
    "PulseTrainOutput",
    "PulseType",
    "QuadratureDecodeMode",
    "QuadratureDecoder",
    "QueueStrategy",
    "RawLogging",
    "Recording",
    "ReferenceTrigger",
    "RepetitiveOneShotOutput",
    "ResistanceInput",
    "RetriggerMode",
    "RetriggerSpec",
    "RtdInput",
    "RtdType",
    "SdkEventKind",
    "SensorStatus",
    "SoftwareStart",
    "StrainExcitationSource",
    "StrainGageConfiguration",
    "StrainGageTeds",
    "StrainInput",
    "SubsystemInfo",
    "SubsystemState",
    "SubsystemType",
    "SyncBusStart",
    "Tachometer",
    "TaskBuilder",
    "TaskSpec",
    "TemperatureUnit",
    "ThermistorInput",
    "ThermocoupleInput",
    "ThermocoupleType",
    "Timing",
    "TriggerSpec",
    "WrapMode",
    "__version__",
    "block_to_long_rows",
    "block_to_rows",
    "bridge_value_from_volts",
    "channel_from_dict",
    "compute_delta_rosette",
    "compute_rectangular_rosette",
    "config_from_env",
    "convert_temperature_to_volts",
    "convert_volts_to_temperature",
    "find_devices",
    "find_subsystems",
    "get_thermocouple_range",
    "open_device",
    "play",
    "read_bridge_sensor_teds",
    "read_bridge_sensor_virtual_teds",
    "read_strain_gage_teds",
    "read_strain_gage_virtual_teds",
    "reading_to_row",
    "record",
    "record_polled",
    "strain_from_volts",
    "to_pint",
]
